[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
remappings = [
    '@abacus-network/=node_modules/@abacus-network/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@summa-tx/=node_modules/@summa-tx/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'prettier-plugin-solidity/=node_modules/prettier-plugin-solidity/',
]
# via-ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config